admin-register: 'd-6c7e4887e7c7462ab9b66b85cc4cd117'
admin-reset-password: 'd-80b1acb90b2346eda830476e5f3eae38'
user-received-contact: 'd-b91d425a9c3b4172b27d32d4873e47b5'
user-order-authorized: 'd-be6a54c1aefd4ed4889994487a0b0d66'
user-order-shipped: 'd-45607d91970c4791a15da0fa8becf9cc'
user-start-live: 'd-7205bbfbef054ca6b8976b2e399cd42a'
